security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    providers:
        users_in_memory:
            memory:
                users: {'%env(EMAIL)%': { password: '%env(ENCODED_PASSWORD)%', roles: ['ROLE_ADMIN'] }}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
                provider: users_in_memory
            logout:
                path: /logout
                target: /
                invalidate_session: true

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/admin', roles: ROLE_ADMIN }
