security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    providers:
        users_in_memory:
            memory:
                users: {'%env(EMAIL)%': { password: '%env(ENCODED_PASSWORD)%', roles: ['ROLE_ADMIN'] }}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/admin/
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
                provider: users_in_memory
            logout:
                path: app_logout

        login_logout:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
                provider: users_in_memory
