twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        themeColor1: '%env(THEME_COLOR_1)%'
        themeColor2: '%env(THEME_COLOR_2)%'
        themeColor3: '%env(THEME_COLOR_3)%'
