language: php
php:
    - 7.4

services:
    - elasticsearch

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.8.1-amd64.deb && sudo service elasticsearch restart

#ElasticSearch takes few seconds to start, to make sure it is available when the build script runs add a small delay to your build script:
before_script:
    - sleep 10

env:
    - ELASTICSEARCH_URL="http://127.0.0.1:9200"

install:
    - composer install
    - npm install
    - npm run build

script:
    - bin/console app:phpunit
    - bin/phpunit
