theme: jekyll-theme-cayman
google_site_verification: JhQeRDOcxzM8KPEnU6AL4MXH8lrGSBAPwafRSyLbVf8
title: "elasticsearch-admin | Web administration for Elasticsearch"
description: "Web admin interface to manage cluster, nodes, indices, shards, index templates, repositories, snapshots ..."
