name: phpunit

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                stack-version: [7.9.0]

        steps:
            - uses: actions/checkout@v2
            - name: Configure sysctl limits
              run: |
                    sudo swapoff -a
                    sudo sysctl -w vm.swappiness=1
                    sudo sysctl -w fs.file-max=262144
                    sudo sysctl -w vm.max_map_count=262144
            - name: Runs Elasticsearch
              uses: elastic/elastic-github-actions/elasticsearch@master
              with:
                    stack-version: ${{ matrix.stack-version }}
                    port: 9200

            - name: Sleep for 30 seconds
              uses: jakejarvis/wait-action@master
              with:
                    time: '30s'

            - uses: php-actions/composer@v1

            - name: Setup PHP
              uses: nanasess/setup-php@master
              with:
                    php-version: 7.4
              env:
                    ELASTICSEARCH_URL: 127.0.0.1:9200

            - run: |
                mkdir var/cache
                bin/console app:phpunit
                bin/phpunit
